import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.overview': 'Overview',
    'nav.shop': 'Shop',
    'nav.cart': 'Cart',
    'nav.orders': 'My Orders',
    'nav.wallet': 'Wallet',
    'nav.team': 'My Team',
    'nav.rank': 'Rank Progress',
    'nav.pv': 'PV History',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    'nav.logout': 'Log Out',
    'nav.users': 'Users',
    'nav.managers': 'Managers',
    'nav.products': 'Products',
    'nav.inventory': 'Inventory',
    'nav.orderManagement': 'Orders',
    'nav.promotions': 'Promotions',
    'nav.approvals': 'Approvals',
    'nav.accounts': 'Accounts',
    'nav.ranks': 'Ranks',
    'nav.codes': 'Codes',
    'nav.deals': 'Deals',
    'nav.paymentSettings': 'Payments',
    'nav.switchToUser': 'Switch to User View',
    'nav.switchToAdmin': 'Switch to Admin View',
    'admin.dashboard': 'Admin Dashboard',
    'admin.platformOverview': 'Platform overview and key metrics',
    'admin.totalUsers': 'Total Users',
    'admin.active': 'active',
    'admin.totalPV': 'Total PV in System',
    'admin.pendingOrders': 'Pending Orders',
    'admin.pendingPromotions': 'Pending Promotions',
    'admin.payments': 'Payments (Last 7 days)',
    'admin.systemStatus': 'System Status',
    'admin.operational': 'Operational',
    'admin.welcome': 'Welcome to the Admin Dashboard',
    'admin.welcomeDesc': 'Manage your community platform, configure ranks, approve promotions, and oversee all operations from this central hub.',
    'admin.quickActions': 'Quick Actions',
    'admin.approvals': 'Approvals',
    'admin.settings': 'Settings',
    'user.dashboard': 'Dashboard',
    'user.welcome': 'Welcome back',
    'user.overviewSubtitle': "Here's your community overview",
    'user.currentRank': 'Current Rank',
    'user.totalPV': 'Total PV',
    'user.teamMembers': 'Team Members',
    'user.walletBalance': 'Wallet Balance',
    'user.nextRank': 'Next Rank',
    'user.pvNeeded': 'PV needed',
    'user.recentActivity': 'Recent Activity',
    'user.viewAll': 'View All',
    'user.noActivity': 'No recent activity',
    'user.activeBranches': 'Active Branches',
    'user.progressTo': 'Progress to',
    'user.requiredPV': 'Required PV',
    'user.requiredBranches': 'Required Branches',
    'shop.title': 'Shop',
    'shop.search': 'Search products...',
    'shop.allCategories': 'All Categories',
    'shop.addToCart': 'Add to Cart',
    'shop.outOfStock': 'Out of Stock',
    'shop.pv': 'PV',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'orders.title': 'My Orders',
    'orders.noOrders': 'No orders yet',
    'orders.status': 'Status',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.items': 'Items',
    'orders.pending': 'Pending',
    'orders.confirmed': 'Confirmed',
    'orders.shipped': 'Shipped',
    'orders.delivered': 'Delivered',
    'orders.cancelled': 'Cancelled',
    'wallet.title': 'Wallet',
    'wallet.balance': 'Current Balance',
    'wallet.transactions': 'Transaction History',
    'wallet.noTransactions': 'No transactions yet',
    'wallet.credit': 'Credit',
    'wallet.debit': 'Debit',
    'team.title': 'My Team',
    'team.directRecruits': 'Direct Recruits',
    'team.totalTeam': 'Total Team',
    'team.noMembers': 'No team members yet',
    'team.inviteCode': 'Your Invite Code',
    'team.copyCode': 'Copy Code',
    'team.copied': 'Copied!',
    'rank.title': 'Rank Progress',
    'rank.current': 'Current Rank',
    'rank.next': 'Next Rank',
    'rank.progress': 'Progress',
    'rank.requirements': 'Requirements',
    'rank.benefits': 'Benefits',
    'pv.title': 'PV History',
    'pv.total': 'Total PV',
    'pv.personal': 'Personal PV',
    'pv.team': 'Team PV',
    'pv.noHistory': 'No PV history yet',
    'profile.title': 'Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.country': 'Country',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'auth.login': 'Log In',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.actions': 'Actions',
    'common.processing': 'Processing...',
    'common.uploading': 'Uploading...',
    'common.adding': 'Adding...',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.inStock': 'In Stock',
    'common.na': 'N/A',
    'common.totalMembers': 'Total Members',
    'common.copyId': 'Copy ID',
    'common.rank': 'Rank',
    'common.role': 'Role',
    'common.status': 'Status',
    'common.user': 'User',
    'common.admin': 'Admin',
    'common.manager': 'Manager',
    'common.placeOrder': 'Place Order',
    'common.orderNow': 'Order Now',
    'shop.subtitle': 'Purchase products and earn PV points',
    'shop.noProducts': 'No products available in this category',
    'shop.priceNotSet': 'Price not set',
    'shop.unitPrice': 'Unit Price',
    'shop.totalAmount': 'Total Amount',
    'shop.youSave': 'You save',
    'shop.orderPending': 'Your order will be pending until approved by the stockist.',
    'cart.subtitle': 'Review and checkout your selected items',
    'cart.emptySubtitle': 'Start shopping to add products to your cart',
    'cart.orderSummary': 'Order Summary',
    'cart.freeItems': 'Free Items',
    'cart.insufficientBalance': 'Insufficient wallet balance',
    'cart.topUpWallet': 'Top up your wallet to place an order',
    'cart.proceedCheckout': 'Proceed to Checkout',
    'cart.walletDeduction': 'Order amount will be deducted from your wallet',
    'cart.lifeChangerCode': 'Life Changer Code (Optional)',
    'cart.enterCode': 'Enter code for bonus PV',
    'wallet.availableBalance': 'Available Balance',
    'wallet.addMoney': 'Add Money',
    'wallet.addMoneyViaCard': 'Add Money via Card',
    'wallet.amount': 'Amount',
    'wallet.note': 'Note:',
    'wallet.demoNote': 'This is a demo implementation. In production, use a payment gateway.',
    'wallet.balanceAfter': 'Balance after',
    'orders.submitPaymentProof': 'Submit Payment Proof',
    'orders.paymentProofSubmitted': 'Payment Proof Submitted',
    'orders.adminNotes': 'Admin Notes',
    'orders.totalOrders': 'Total Orders',
    'orders.totalAmount': 'Total Amount',
    'orders.awaitingPayment': 'Awaiting Payment',
    'profile.subtitle': 'Manage your personal information and preferences',
    'profile.accountInfo': 'Account Information',
    'profile.emailCantChange': 'Email cannot be changed',
    'profile.memberSince': 'Member Since',
    'profile.deliveryAddress': 'Delivery Address',
    'profile.deliveryAddressDesc': 'This address will be used for product delivery',
    'profile.streetAddress': 'Street Address',
    'profile.apartment': 'Apartment, Suite, etc. (Optional)',
    'profile.city': 'City',
    'profile.stateProvince': 'State / Province',
    'profile.postalCode': 'Postal Code',
    'profile.importantNote': 'Important Note:',
    'profile.countryChangeWarning': 'Changing your country will affect which products and prices you see.',
    'profile.uploadPhoto': 'Click camera to upload',
    'profile.maxSize': 'Max 5MB, JPG/PNG/GIF',
    'profile.selectCountry': 'Select a country',
    'profile.currencyNote': 'Products will be shown in this currency',
    'team.subtitle': 'Your direct referrals and their progress',
    'team.referralLink': 'Your Referral Link',
    'team.shareIdInfo': 'Share your user ID with new members',
    'team.noMembersSubtitle': 'Start building your team by sharing your referral code',
    'admin.userManagement': 'User Management',
    'admin.manageUsers': 'Manage all platform users',
    'admin.searchUsers': 'Search users by name or email...',
    'admin.orderProcessing': 'Order Processing Workflow',
    'admin.paymentSubmitted': 'Payment Submitted',
    'admin.verifyPayment': 'Verify payment proof. Confirm or reject.',
    'admin.loadingPending': 'Loading pending accounts...',
    'admin.loadingOrders': 'Loading orders...',
    'admin.loadingCodes': 'Loading codes...',
    'admin.loadingTeam': 'Loading team management...',
    'admin.loadingInventory': 'Loading inventory...',
    'admin.confirmRejection': 'Confirm Rejection',
    'admin.editCode': 'Edit Life Changer Code',
    'admin.addCode': 'Add Life Changer Code',
    'admin.addManager': 'Add Manager',
    'admin.editPermissions': 'Edit Permissions',
    'admin.fullAccess': 'Full Access',
    'admin.addProduct': 'Add New Product',
    'admin.editProduct': 'Edit Product',
    'admin.uploadImage': 'Upload Image',
    'admin.editPromotion': 'Edit Promotion',
    'admin.createPromotion': 'Create Promotion',
    'admin.createFirstDeal': 'Create your first "Buy X Get Y Free" deal',
    'admin.buyXGetYFree': 'Create "Buy X Get Y Free" deals for products',
    'admin.expired': 'Expired',
    'admin.pause': 'Pause',
    'admin.activate': 'Activate',
    'admin.addInventory': 'Add Product Inventory',
    'admin.updating': 'Updating...',
    'notifications.title': 'Notifications',
    'notifications.noNotifications': 'No notifications',
    'pv.totalEarned': 'Total Earned',
    'pv.totalSpent': 'Total Spent',
  },
  fr: {
    'nav.overview': 'Apercu',
    'nav.shop': 'Boutique',
    'nav.cart': 'Panier',
    'nav.orders': 'Mes Commandes',
    'nav.wallet': 'Portefeuille',
    'nav.team': 'Mon Equipe',
    'nav.rank': 'Progression',
    'nav.pv': 'Historique PV',
    'nav.profile': 'Profil',
    'nav.notifications': 'Notifications',
    'nav.logout': 'Deconnexion',
    'nav.users': 'Utilisateurs',
    'nav.managers': 'Gestionnaires',
    'nav.products': 'Produits',
    'nav.inventory': 'Inventaire',
    'nav.orderManagement': 'Commandes',
    'nav.promotions': 'Promotions',
    'nav.approvals': 'Approbations',
    'nav.accounts': 'Comptes',
    'nav.ranks': 'Rangs',
    'nav.codes': 'Codes',
    'nav.deals': 'Offres',
    'nav.paymentSettings': 'Paiements',
    'nav.switchToUser': 'Passer en Vue Utilisateur',
    'nav.switchToAdmin': 'Passer en Vue Admin',
    'admin.dashboard': 'Tableau de Bord Admin',
    'admin.platformOverview': 'Apercu de la plateforme et indicateurs cles',
    'admin.totalUsers': 'Utilisateurs Total',
    'admin.active': 'actifs',
    'admin.totalPV': 'PV Total du Systeme',
    'admin.pendingOrders': 'Commandes en Attente',
    'admin.pendingPromotions': 'Promotions en Attente',
    'admin.payments': 'Paiements (7 derniers jours)',
    'admin.systemStatus': 'Etat du Systeme',
    'admin.operational': 'Operationnel',
    'admin.welcome': 'Bienvenue sur le Tableau de Bord Admin',
    'admin.welcomeDesc': 'Gerez votre plateforme communautaire, configurez les rangs, approuvez les promotions et supervisez toutes les operations depuis ce hub central.',
    'admin.quickActions': 'Actions Rapides',
    'admin.approvals': 'Approbations',
    'admin.settings': 'Parametres',
    'user.dashboard': 'Tableau de Bord',
    'user.welcome': 'Bienvenue',
    'user.overviewSubtitle': 'Voici votre apercu communautaire',
    'user.currentRank': 'Rang Actuel',
    'user.totalPV': 'PV Total',
    'user.teamMembers': 'Membres de l\'Equipe',
    'user.walletBalance': 'Solde du Portefeuille',
    'user.nextRank': 'Prochain Rang',
    'user.pvNeeded': 'PV necessaires',
    'user.recentActivity': 'Activite Recente',
    'user.viewAll': 'Voir Tout',
    'user.noActivity': 'Aucune activite recente',
    'user.activeBranches': 'Branches Actives',
    'user.progressTo': 'Progression vers',
    'user.requiredPV': 'PV Requis',
    'user.requiredBranches': 'Branches Requises',
    'shop.title': 'Boutique',
    'shop.search': 'Rechercher des produits...',
    'shop.allCategories': 'Toutes les Categories',
    'shop.addToCart': 'Ajouter au Panier',
    'shop.outOfStock': 'Rupture de Stock',
    'shop.pv': 'PV',
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.subtotal': 'Sous-total',
    'cart.total': 'Total',
    'cart.checkout': 'Commander',
    'cart.continueShopping': 'Continuer les Achats',
    'cart.remove': 'Supprimer',
    'orders.title': 'Mes Commandes',
    'orders.noOrders': 'Aucune commande',
    'orders.status': 'Statut',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.items': 'Articles',
    'orders.pending': 'En Attente',
    'orders.confirmed': 'Confirmee',
    'orders.shipped': 'Expediee',
    'orders.delivered': 'Livree',
    'orders.cancelled': 'Annulee',
    'wallet.title': 'Portefeuille',
    'wallet.balance': 'Solde Actuel',
    'wallet.transactions': 'Historique des Transactions',
    'wallet.noTransactions': 'Aucune transaction',
    'wallet.credit': 'Credit',
    'wallet.debit': 'Debit',
    'team.title': 'Mon Equipe',
    'team.directRecruits': 'Recrutes Directs',
    'team.totalTeam': 'Equipe Totale',
    'team.noMembers': 'Aucun membre dans l\'equipe',
    'team.inviteCode': 'Votre Code d\'Invitation',
    'team.copyCode': 'Copier le Code',
    'team.copied': 'Copie!',
    'rank.title': 'Progression de Rang',
    'rank.current': 'Rang Actuel',
    'rank.next': 'Prochain Rang',
    'rank.progress': 'Progression',
    'rank.requirements': 'Exigences',
    'rank.benefits': 'Avantages',
    'pv.title': 'Historique PV',
    'pv.total': 'PV Total',
    'pv.personal': 'PV Personnel',
    'pv.team': 'PV Equipe',
    'pv.noHistory': 'Aucun historique PV',
    'profile.title': 'Profil',
    'profile.fullName': 'Nom Complet',
    'profile.email': 'Email',
    'profile.phone': 'Telephone',
    'profile.country': 'Pays',
    'profile.save': 'Enregistrer',
    'profile.saving': 'Enregistrement...',
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.forgotPassword': 'Mot de passe oublie?',
    'auth.noAccount': 'Pas de compte?',
    'auth.hasAccount': 'Deja un compte?',
    'auth.signUp': 'S\'inscrire',
    'auth.signIn': 'Se connecter',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succes',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.actions': 'Actions',
    'common.processing': 'Traitement...',
    'common.uploading': 'Telechargement...',
    'common.adding': 'Ajout...',
    'common.active': 'Actif',
    'common.inactive': 'Inactif',
    'common.inStock': 'En Stock',
    'common.na': 'N/A',
    'common.totalMembers': 'Membres Total',
    'common.copyId': 'Copier ID',
    'common.rank': 'Rang',
    'common.role': 'Role',
    'common.status': 'Statut',
    'common.user': 'Utilisateur',
    'common.admin': 'Admin',
    'common.manager': 'Gestionnaire',
    'common.placeOrder': 'Passer la Commande',
    'common.orderNow': 'Commander',
    'shop.subtitle': 'Achetez des produits et gagnez des points PV',
    'shop.noProducts': 'Aucun produit disponible dans cette categorie',
    'shop.priceNotSet': 'Prix non defini',
    'shop.unitPrice': 'Prix Unitaire',
    'shop.totalAmount': 'Montant Total',
    'shop.youSave': 'Vous economisez',
    'shop.orderPending': 'Votre commande sera en attente jusqu\'a approbation par le stockiste.',
    'cart.subtitle': 'Verifiez et finalisez vos articles selectionnes',
    'cart.emptySubtitle': 'Commencez vos achats pour ajouter des produits',
    'cart.orderSummary': 'Resume de la Commande',
    'cart.freeItems': 'Articles Gratuits',
    'cart.insufficientBalance': 'Solde insuffisant',
    'cart.topUpWallet': 'Rechargez votre portefeuille pour passer commande',
    'cart.proceedCheckout': 'Proceder au Paiement',
    'cart.walletDeduction': 'Le montant sera deduit de votre portefeuille',
    'cart.lifeChangerCode': 'Code Life Changer (Optionnel)',
    'cart.enterCode': 'Entrez le code pour bonus PV',
    'wallet.availableBalance': 'Solde Disponible',
    'wallet.addMoney': 'Ajouter des Fonds',
    'wallet.addMoneyViaCard': 'Ajouter des Fonds par Carte',
    'wallet.amount': 'Montant',
    'wallet.note': 'Note:',
    'wallet.demoNote': 'Ceci est une implementation de demonstration. En production, utilisez une passerelle de paiement.',
    'wallet.balanceAfter': 'Solde apres',
    'orders.submitPaymentProof': 'Soumettre la Preuve de Paiement',
    'orders.paymentProofSubmitted': 'Preuve de Paiement Soumise',
    'orders.adminNotes': 'Notes Admin',
    'orders.totalOrders': 'Commandes Totales',
    'orders.totalAmount': 'Montant Total',
    'orders.awaitingPayment': 'En Attente de Paiement',
    'profile.subtitle': 'Gerez vos informations personnelles et preferences',
    'profile.accountInfo': 'Informations du Compte',
    'profile.emailCantChange': 'L\'email ne peut pas etre modifie',
    'profile.memberSince': 'Membre Depuis',
    'profile.deliveryAddress': 'Adresse de Livraison',
    'profile.deliveryAddressDesc': 'Cette adresse sera utilisee pour la livraison',
    'profile.streetAddress': 'Adresse',
    'profile.apartment': 'Appartement, Suite, etc. (Optionnel)',
    'profile.city': 'Ville',
    'profile.stateProvince': 'Province / Etat',
    'profile.postalCode': 'Code Postal',
    'profile.importantNote': 'Note Importante:',
    'profile.countryChangeWarning': 'Changer de pays affectera les produits et prix affiches.',
    'profile.uploadPhoto': 'Cliquez pour telecharger',
    'profile.maxSize': 'Max 5Mo, JPG/PNG/GIF',
    'profile.selectCountry': 'Selectionnez un pays',
    'profile.currencyNote': 'Les produits seront affiches dans cette devise',
    'team.subtitle': 'Vos parrainages directs et leur progression',
    'team.referralLink': 'Votre Lien de Parrainage',
    'team.shareIdInfo': 'Partagez votre ID avec les nouveaux membres',
    'team.noMembersSubtitle': 'Construisez votre equipe en partageant votre code',
    'admin.userManagement': 'Gestion des Utilisateurs',
    'admin.manageUsers': 'Gerer tous les utilisateurs de la plateforme',
    'admin.searchUsers': 'Rechercher par nom ou email...',
    'admin.orderProcessing': 'Traitement des Commandes',
    'admin.paymentSubmitted': 'Paiement Soumis',
    'admin.verifyPayment': 'Verifiez la preuve de paiement. Confirmez ou rejetez.',
    'admin.loadingPending': 'Chargement des comptes en attente...',
    'admin.loadingOrders': 'Chargement des commandes...',
    'admin.loadingCodes': 'Chargement des codes...',
    'admin.loadingTeam': 'Chargement de la gestion d\'equipe...',
    'admin.loadingInventory': 'Chargement de l\'inventaire...',
    'admin.confirmRejection': 'Confirmer le Rejet',
    'admin.editCode': 'Modifier le Code Life Changer',
    'admin.addCode': 'Ajouter un Code Life Changer',
    'admin.addManager': 'Ajouter un Gestionnaire',
    'admin.editPermissions': 'Modifier les Permissions',
    'admin.fullAccess': 'Acces Complet',
    'admin.addProduct': 'Ajouter un Produit',
    'admin.editProduct': 'Modifier le Produit',
    'admin.uploadImage': 'Telecharger une Image',
    'admin.editPromotion': 'Modifier la Promotion',
    'admin.createPromotion': 'Creer une Promotion',
    'admin.createFirstDeal': 'Creez votre premiere offre "Achetez X Obtenez Y Gratuit"',
    'admin.buyXGetYFree': 'Creez des offres "Achetez X Obtenez Y Gratuit"',
    'admin.expired': 'Expire',
    'admin.pause': 'Pause',
    'admin.activate': 'Activer',
    'admin.addInventory': 'Ajouter a l\'Inventaire',
    'admin.updating': 'Mise a jour...',
    'notifications.title': 'Notifications',
    'notifications.noNotifications': 'Aucune notification',
    'pv.totalEarned': 'Total Gagne',
    'pv.totalSpent': 'Total Depense',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'fr' || saved === 'en') ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
