INSERT INTO products (name, product_type, pv_value, description, is_active) VALUES
  ('Savon au Charbon de Bambou', 'Physical', 6, 'Soap made with bamboo charcoal', true),
  ('Savon au Thé Blanc', 'Physical', 2.8, 'White tea soap', true),
  ('Gel Douche', 'Physical', 6, 'Body wash gel', true),
  ('Gel Olive', 'Physical', 8, 'Olive-based shower gel', true),
  ('Gel de Serpent', 'Physical', 3, 'Herbal gel', true),
  ('Lait SOD', 'Physical', 4, 'Skin care milk', true),
  ('Lotion Rajeunissante', 'Physical', 3.8, 'Rejuvenating lotion', true),
  ('Acide Hyaluronique', 'Supplement', 5, 'Hyaluronic acid supplement', true),
  ('Crème de Mains', 'Physical', 3.5, 'Hand cream', true),
  ('Antisudorifique', 'Physical', 3.5, 'Anti-perspirant product', true),
  ('Pâte Dentifrice au Thé Blanc 200g', 'Physical', 3.5, 'White tea toothpaste (200g)', true),
  ('Pâte Dentifrice au Thé Blanc 100g', 'Physical', 1.2, 'White tea toothpaste (100g)', true),
  ('Spray de Bouche', 'Physical', 3, 'Oral spray', true),
  ('Protèges Slips', 'Physical', 50, 'Sanitary liners', true),
  ('Serviettes Hygiéniques', 'Physical', 50, 'Sanitary pads', true),
  ('Cordyceps Militaris', 'Supplement', 70, 'Cordyceps mushroom supplement', true),
  ('Vitamine C', 'Supplement', 8, 'Vitamin C supplement', true),
  ('Arthro', 'Supplement', 20, 'Joint health supplement', true),
  ('Thé', 'Beverage', 5, 'Herbal tea', true),
  ('Café Cordyceps', 'Beverage', 3, 'Coffee with cordyceps', true),
  ('Berry Oil', 'Supplement', 30, 'Berry-based oil', true),
  ('Menquian', 'Supplement', 20, 'Herbal supplement', true),
  ('Calcium', 'Supplement', 11, 'Calcium supplement', true),
  ('Libao', 'Supplement', 20, 'Herbal health product', true),
  ('Vin de Santé', 'Beverage', 9, 'Health wine', true),
  ('Gobelet Alcalin', 'Accessory', 45, 'Alkaline cup', true),
  ('Marmite', 'Accessory', 170, 'Cooking pot', true);