/*
  # Add continent column to countries

  1. Changes
    - Adds a `continent` text column to the `countries` table
    - Populates continent for all existing countries based on their ISO codes
    - Continents: Africa, Asia, Europe, North America, South America, Oceania, Antarctica

  2. Notes
    - Column is nullable to handle edge cases
    - Uses standard continent groupings per ISO 3166-1 alpha-2 codes
*/

ALTER TABLE countries ADD COLUMN IF NOT EXISTS continent text;

UPDATE countries SET continent = CASE code
  -- Africa
  WHEN 'EG' THEN 'Africa'
  WHEN 'ET' THEN 'Africa'
  WHEN 'GH' THEN 'Africa'
  WHEN 'KE' THEN 'Africa'
  WHEN 'MA' THEN 'Africa'
  WHEN 'NG' THEN 'Africa'
  WHEN 'RE' THEN 'Africa'
  WHEN 'RW' THEN 'Africa'
  WHEN 'SH' THEN 'Africa'
  WHEN 'TZ' THEN 'Africa'
  WHEN 'UG' THEN 'Africa'
  WHEN 'YT' THEN 'Africa'
  WHEN 'ZA' THEN 'Africa'
  WHEN 'EH' THEN 'Africa'
  -- Asia
  WHEN 'AE' THEN 'Asia'
  WHEN 'BD' THEN 'Asia'
  WHEN 'CN' THEN 'Asia'
  WHEN 'HK' THEN 'Asia'
  WHEN 'ID' THEN 'Asia'
  WHEN 'IL' THEN 'Asia'
  WHEN 'IN' THEN 'Asia'
  WHEN 'IO' THEN 'Asia'
  WHEN 'JP' THEN 'Asia'
  WHEN 'KR' THEN 'Asia'
  WHEN 'MO' THEN 'Asia'
  WHEN 'MY' THEN 'Asia'
  WHEN 'PH' THEN 'Asia'
  WHEN 'PK' THEN 'Asia'
  WHEN 'PS' THEN 'Asia'
  WHEN 'SA' THEN 'Asia'
  WHEN 'SG' THEN 'Asia'
  WHEN 'TH' THEN 'Asia'
  WHEN 'TL' THEN 'Asia'
  WHEN 'TR' THEN 'Asia'
  WHEN 'TW' THEN 'Asia'
  WHEN 'VN' THEN 'Asia'
  -- Europe
  WHEN 'AD' THEN 'Europe'
  WHEN 'AT' THEN 'Europe'
  WHEN 'AX' THEN 'Europe'
  WHEN 'BE' THEN 'Europe'
  WHEN 'CH' THEN 'Europe'
  WHEN 'CZ' THEN 'Europe'
  WHEN 'DE' THEN 'Europe'
  WHEN 'DK' THEN 'Europe'
  WHEN 'ES' THEN 'Europe'
  WHEN 'FI' THEN 'Europe'
  WHEN 'FO' THEN 'Europe'
  WHEN 'FR' THEN 'Europe'
  WHEN 'GB' THEN 'Europe'
  WHEN 'GG' THEN 'Europe'
  WHEN 'GI' THEN 'Europe'
  WHEN 'GL' THEN 'Europe'
  WHEN 'GR' THEN 'Europe'
  WHEN 'IE' THEN 'Europe'
  WHEN 'IM' THEN 'Europe'
  WHEN 'IT' THEN 'Europe'
  WHEN 'JE' THEN 'Europe'
  WHEN 'LI' THEN 'Europe'
  WHEN 'MC' THEN 'Europe'
  WHEN 'NL' THEN 'Europe'
  WHEN 'NO' THEN 'Europe'
  WHEN 'PL' THEN 'Europe'
  WHEN 'PT' THEN 'Europe'
  WHEN 'RO' THEN 'Europe'
  WHEN 'SE' THEN 'Europe'
  WHEN 'SJ' THEN 'Europe'
  WHEN 'SM' THEN 'Europe'
  WHEN 'VA' THEN 'Europe'
  WHEN 'XK' THEN 'Europe'
  -- North America
  WHEN 'AI' THEN 'North America'
  WHEN 'BB' THEN 'North America'
  WHEN 'BL' THEN 'North America'
  WHEN 'BM' THEN 'North America'
  WHEN 'BQ' THEN 'North America'
  WHEN 'CA' THEN 'North America'
  WHEN 'CR' THEN 'North America'
  WHEN 'CX' THEN 'North America'
  WHEN 'KY' THEN 'North America'
  WHEN 'MF' THEN 'North America'
  WHEN 'MQ' THEN 'North America'
  WHEN 'MS' THEN 'North America'
  WHEN 'MX' THEN 'North America'
  WHEN 'PA' THEN 'North America'
  WHEN 'PM' THEN 'North America'
  WHEN 'SX' THEN 'North America'
  WHEN 'TC' THEN 'North America'
  WHEN 'TT' THEN 'North America'
  WHEN 'UM' THEN 'North America'
  WHEN 'US' THEN 'North America'
  WHEN 'VG' THEN 'North America'
  WHEN 'VI' THEN 'North America'
  WHEN 'GP' THEN 'North America'
  WHEN 'JM' THEN 'North America'
  -- South America
  WHEN 'AR' THEN 'South America'
  WHEN 'BR' THEN 'South America'
  WHEN 'BV' THEN 'South America'
  WHEN 'CL' THEN 'South America'
  WHEN 'CO' THEN 'South America'
  WHEN 'EC' THEN 'South America'
  WHEN 'FK' THEN 'South America'
  WHEN 'GF' THEN 'South America'
  WHEN 'GS' THEN 'South America'
  WHEN 'PE' THEN 'South America'
  WHEN 'VE' THEN 'South America'
  -- Oceania
  WHEN 'AS' THEN 'Oceania'
  WHEN 'AU' THEN 'Oceania'
  WHEN 'CC' THEN 'Oceania'
  WHEN 'CK' THEN 'Oceania'
  WHEN 'GU' THEN 'Oceania'
  WHEN 'HM' THEN 'Oceania'
  WHEN 'MP' THEN 'Oceania'
  WHEN 'NC' THEN 'Oceania'
  WHEN 'NF' THEN 'Oceania'
  WHEN 'NU' THEN 'Oceania'
  WHEN 'NZ' THEN 'Oceania'
  WHEN 'PF' THEN 'Oceania'
  WHEN 'PN' THEN 'Oceania'
  WHEN 'TF' THEN 'Oceania'
  WHEN 'TK' THEN 'Oceania'
  WHEN 'WF' THEN 'Oceania'
  -- Antarctica
  WHEN 'AQ' THEN 'Antarctica'
  ELSE NULL
END;
